Setup

In [1]:
import numpy as np
import time

Section 1 — ndarray Fundamentals

Task 1.1: Array Creation & Shapes

In [2]:
# TODO:
# Create a 1D array with values 0 to 99 (no loops)

# HINT:
# - Use np.arange

arr_1d = np.arange(100)
arr_1d


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [3]:
# TODO:
# Reshape arr_1d into a (10, 10) array

# HINT:
# - reshape does NOT copy data

arr_2d = arr_1d.reshape(10,10)
arr_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [6]:
# TODO:
# Create a 3D array of shape (4, 5, 3)

# HINT:
# - Total elements must match

arr_3d = np.arange(4*5*3).reshape(4,5,3)
arr_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

**Explain:**
- What does `.shape` represent?  :  Represents the dimension of the numpy array
- Why does contiguous memory matter?  : allows access to the elements using the index in the array


Section 1.2 — dtype & Memory

In [4]:
# TODO:
# Create two arrays with same values but different dtypes

arr=np.arange(100)
arr_int = arr.astype(np.int64)
arr_float = arr.astype(np.float64)


In [5]:
# TODO:
# Compare memory usage

# HINT:
# - Use .nbytes
print(arr_int.nbytes)
print(arr_float.nbytes)


800
800


**Interview Question:**  
Why does dtype selection matter in large ML pipelines?  : It matters because of right computataion, memory allocation and use case.

Section 2 — Indexing, Views & Copies

Task 2.1: Views vs Copies

In [8]:
# TODO:
# Create a 2D array and slice every alternate row

# HINT:
# - Use slicing, not fancy indexing

A = np.arange(40).reshape(10,4)
A_slice = A[::2]
print('A', A)
print('A_slice', A_slice)


A [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
A_slice [[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]
 [24 25 26 27]
 [32 33 34 35]]


In [12]:
# TODO:
# Modify A_slice and observe A

A_slice[0,0]=-99
A_copy=A[[0,2,4]]
A_copy[0,0]=123

print('A', A)
print('A_slice', A_slice)
print('A_copy', A_copy)



A [[-99   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]
 [ 16  17  18  19]
 [ 20  21  22  23]
 [ 24  25  26  27]
 [ 28  29  30  31]
 [ 32  33  34  35]
 [ 36  37  38  39]]
A_slice [[-99   1   2   3]
 [  8   9  10  11]
 [ 16  17  18  19]
 [ 24  25  26  27]
 [ 32  33  34  35]]
A_copy [[123   1   2   3]
 [  8   9  10  11]
 [ 16  17  18  19]]


Explain:
- Why did the original array change (or not)? :   the original array changed as it shares the same memory and other one is copyied array so it did not change in the copy


Section 2.2 — Boolean Masking

In [4]:
# TODO:
# Create random array of size 1000

range = np.random.default_rng(0)
X=range.standard_normal(1000)
X

array([ 1.25730221e-01, -1.32104863e-01,  6.40422650e-01,  1.04900117e-01,
       -5.35669373e-01,  3.61595055e-01,  1.30400005e+00,  9.47080963e-01,
       -7.03735236e-01, -1.26542147e+00, -6.23274463e-01,  4.13259793e-02,
       -2.32503077e+00, -2.18791664e-01, -1.24591095e+00, -7.32267355e-01,
       -5.44258983e-01, -3.16300156e-01,  4.11630536e-01,  1.04251337e+00,
       -1.28534663e-01,  1.36646347e+00, -6.65194673e-01,  3.51510070e-01,
        9.03470182e-01,  9.40122978e-02, -7.43499249e-01, -9.21725376e-01,
       -4.57725826e-01,  2.20195123e-01, -1.00961818e+00, -2.09175575e-01,
       -1.59225010e-01,  5.40845585e-01,  2.14659123e-01,  3.55372709e-01,
       -6.53828609e-01, -1.29613634e-01,  7.83975470e-01,  1.49343115e+00,
       -1.25906553e+00,  1.51392377e+00,  1.34587542e+00,  7.81311401e-01,
        2.64455630e-01, -3.13922815e-01,  1.45802068e+00,  1.96025832e+00,
        1.80163487e+00,  1.31510376e+00,  3.57380411e-01, -1.20831863e+00,
       -4.45413312e-03,  

In [5]:
# TODO:
# Extract values greater than mean

# HINT:
# - Mean first
# - Boolean mask

mean = np.mean(X)
X_gtm = X[X > mean]
X_gtm


array([ 1.25730221e-01,  6.40422650e-01,  1.04900117e-01,  3.61595055e-01,
        1.30400005e+00,  9.47080963e-01,  4.13259793e-02,  4.11630536e-01,
        1.04251337e+00,  1.36646347e+00,  3.51510070e-01,  9.03470182e-01,
        9.40122978e-02,  2.20195123e-01,  5.40845585e-01,  2.14659123e-01,
        3.55372709e-01,  7.83975470e-01,  1.49343115e+00,  1.51392377e+00,
        1.34587542e+00,  7.81311401e-01,  2.64455630e-01,  1.45802068e+00,
        1.96025832e+00,  1.80163487e+00,  1.31510376e+00,  3.57380411e-01,
       -4.45413312e-03,  6.56474935e-01,  3.95122060e-01,  4.29863695e-01,
        6.96042724e-01,  1.73936788e+00,  3.28969629e-01,  1.58347288e+00,
        1.32036099e+00,  6.33352623e-01,  5.20289743e-02,  6.83686191e-01,
        1.00396158e+00,  1.82201136e+00,  9.35049988e-01,  4.90546138e-02,
        2.00239258e+00,  1.88519193e-01,  6.30411491e-01,  5.81165812e-01,
        1.29455882e+00,  1.68910745e+00,  1.57440828e+00,  2.49785372e-01,
        1.03145308e+00,  

In [6]:
# TODO:
# Replace negative values with 0 (no loops)

X_postive = X.copy()
X_postive[X_postive< 0]=0
X_postive



array([1.25730221e-01, 0.00000000e+00, 6.40422650e-01, 1.04900117e-01,
       0.00000000e+00, 3.61595055e-01, 1.30400005e+00, 9.47080963e-01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.13259793e-02,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 4.11630536e-01, 1.04251337e+00,
       0.00000000e+00, 1.36646347e+00, 0.00000000e+00, 3.51510070e-01,
       9.03470182e-01, 9.40122978e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.20195123e-01, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 5.40845585e-01, 2.14659123e-01, 3.55372709e-01,
       0.00000000e+00, 0.00000000e+00, 7.83975470e-01, 1.49343115e+00,
       0.00000000e+00, 1.51392377e+00, 1.34587542e+00, 7.81311401e-01,
       2.64455630e-01, 0.00000000e+00, 1.45802068e+00, 1.96025832e+00,
       1.80163487e+00, 1.31510376e+00, 3.57380411e-01, 0.00000000e+00,
       0.00000000e+00, 6.56474935e-01, 0.00000000e+00, 3.95122060e-01,
      

Section 3 — Broadcasting

Task 3.1: Broadcasting Rules

In [3]:
# TODO:
# Create A (1000, 50) and b (50,)

range = np.random.default_rng(1)
A = range.standard_normal((1000,50))
b = range.standard_normal((50,))



In [10]:
# TODO:
# Add b to each row of A



# HINT:
# - No reshape required

A_plus=A+b
print(A_plus)

In [21]:
# TODO:
# Normalize each row of A

# HINT:
# - Axis matters
# - Keep dimensions in mind

A_row_mean = A.mean(axis=1, keepdims=True)
A_row_std = A.std(axis=1, keepdims=True)
A_normalized = (A - A_row_mean) / A_row_std
A_normalized


array([[ 0.43315068,  0.97340433,  0.41596014, ..., -0.53364807,
         0.71479328,  1.05233567],
       [ 0.52733678, -0.86313936,  1.02880626, ...,  0.17595973,
        -1.60425078,  0.54194286],
       [-0.59798008,  1.03431279, -0.03111501, ...,  0.56276422,
         0.40885135, -1.14578763],
       ...,
       [ 2.25056304, -0.018768  , -1.57048842, ..., -1.01388747,
        -1.19604393,  2.08579746],
       [ 0.26769991, -0.68685852,  0.02033279, ...,  0.73471841,
        -1.66595491, -0.50375355],
       [-0.33838782, -0.35500852, -0.6645427 , ..., -0.24783664,
        -0.21235055, -0.05953269]])

Explain broadcasting step-by-step.


Section 3.2 — Broadcasting Trap

In [4]:
# TODO:
# Intentionally trigger a broadcasting error
# Then fix it

col=np.arange(1000)
try:
  _=A-col
except ValueError as error:
  print("Broadcasting error:", error)

col2=col.reshape(-1,1)
A_fixed=A-col2
A_fixed.shape

Broadcasting error: operands could not be broadcast together with shapes (1000,50) (1000,) 


(1000, 50)

What was wrong with the original shapes? : because the shape of the original array didn't match




Section 4 — Vectorization vs Loops

Task 4.1: Loop vs Vectorized

In [7]:
# TODO:
# Create large array X of size 1,000,000

X =  np.random.rand(1_000_000)
X


array([0.68116419, 0.55649631, 0.67953063, ..., 0.50458963, 0.20727803,
       0.99403509])

In [2]:
# TODO:
# Normalize using Python loop

# HINT:
# - Time it

# import time
rng = np.random.default_rng(123)
X = rng.standard_normal(1_000_000)

X_mean = np.mean(X)
X_std = np.std(X)

start_time = time.time()

X_normal = np.empty_like(X)
for i in range(X.shape[0]):
    X_normal[i] = (X[i] - X_mean) / X_std

end_time = time.time()
print(f"{round(end_time - start_time, 2)} seconds")



1.27 seconds


In [9]:
# TODO:
# Normalize using vectorization

X_mean = np.mean(X)
X_std = np.std(X)
start_time = time.time()
X_normalized_vectorized = (X - X_mean) / X_std
time_vector = time.time()
X_normalized_vectorized
print(f"{time_vector - start_time} seconds")

0.0040454864501953125 seconds


Why is vectorization faster? : because vectorization performs operation parallely while for loops since it iterates all the elements it is slower


Task 4.2: Pairwise Distance (FAANG Classic)

In [ ]:
# TODO:
# Compute pairwise Euclidean distance matrix without loops

# HINT:
# - Use (x - y)^2 expansion
# - Broadcasting is key

def pairwise_distance(X):
  sq = np.sum(X * X, axis = 1, keepdims = True)
  dist = sq + sq.T - 2 * (X @ X.T)
  dist = np.maximum(dist, 0.0)
  return np.sqrt(dist)

rng = np.random.default_rng(3)
Xsmall = rng.standard_normal((200, 10))
Dist = pairwise_distance(Xsmall)
print(Dist.shape)


Section 5 — Numerical Stability

Task 5.1: Softmax

In [ ]:
# TODO:
# Implement naive softmax


def softmax_naive(X):
  exp = np.exp(X)
  print(exp)
  return exp/exp.sum(axis = 1, keepdims = True)

Xbig = np.array([[1000.0, 1001.0, 1002.0]])
try:
  softmax_naive(Xbig)
except FloatingPointError as e:
  print('overflowerror :', e)


In [ ]:
# TODO:
# Fix numerical instability

# HINT:
# - Subtract max per row

def softmax_stable(X):
    Z = X - X.max(axis = 1, keepdims = True)
    exp = np.exp(Z)
    return exp/exp.sum(axis = 1, keepdims = True)

print('softmax_stable :', softmax_stable(Xbig))
print('softmax_rowSum :', softmax_stable(Xbig).sum(axis = 1))


Why does subtracting max work? :


Section 6 — Linear Algebra

Task 6.1: Matrix Multiplication

In [ ]:
# TODO:
# Try valid and invalid matrix multiplications

X = np.random.default_rng(3).standard_normal((3,4))
Y = np.random.default_rng(4).standard_normal((4,2))
mat_mul = X @ Y
print(mat_multi.shape)

try:
  _ = X @ X
except ValueError as e:
  print('Invalid multiplication: ', e)
print(' X @ Y == dot.product', np.allclose(np.dot(X,Y), mat_multi))
print('matmul == X @ Y', np.allclose(np.matmul(X,Y), mat_multi))

Explain difference between dot, @, and matmul.

the differnce is the optization of each type of computataion.


Task 6.2: Solving Linear Systems

In [ ]:
# TODO:
# Solve Ax = b and verify solution
rng = np.random.default_rng(6)
A = rng.standard_normal((5, 5))
b = rng.standard_normal((5,))
x = np.linalg.solve(A, b)
residual = np.linalg.norm(A @ x - b)
print('residual', residual)

Section 7 — Performance & Memory

Task 7.1: In-Place Operations

In [ ]:
# TODO:
# Compare in-place vs out-of-place operations

X = np.random.default_rng(7).standard_normal((2_000_000))
Y = X.copy()
t = time.time()
Z = X + 1.0
t_out = time.time() - t
t1 = time.time()
Y += 1.0
t_in = time.time() - t1
print('out-of-place :', round(t_out, 4))
print('in-place :', round(t_in, 4))
print(X)
print(Z)


Task 7.2: Strides

In [ ]:
# TODO:
# Inspect array strides and explain

X = np.arange(24).reshape(6, 4)
print('shape :', X.shape, 'strides :', A.strides)
Y = X[:, ::2]
print('shape :', Y.shape, 'strides :', B.strides)

Section 8 — Mini Case Study

In [ ]:
# TODO:
# Given X (10000, 100):
# - Normalize features
# - Compute covariance
# - Extract top-k eigenvectors

range = np.random.default_rng(8)
X = range.standard_normal((10_000, 100))
# Normalize
mu = X.mean(axis = 0, keepdims = True)
sigma = X.std(axis = 0, keepdims = True)
Xn = (X - mu)/sigma
# Covariance
Covariance = (Xn.T @ Xn) / (Xn.shape[0] - 1)
# Top-k Eigenvectors
eigvals, eigvecs = np.linalg.eigh(Covariance)
k = 5
top_idx = np.argsort(eigvals)[-k:][::-1]
top_idx



Explain each step and its ML relevance.


1. Where did NumPy save memory?
2. Where did it avoid Python overhead?
3. Which operation would break at scale?
